language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-angular-components' ]; then cd .. && eval "mv $currentfolder generator-angular-components" && cd generator-angular-components; fi

